### ISSUE TITLE
Add is compatibleinterface to API

### ISSUE THREAD

**Issue by hefee** [OpenSourceOrg/licenses#37]
Often the question comes up if two licenses are work together or not. It would be nice if this can be requested. One common example is that GPL-2.0 and GPL-3.0 are not compatible with each other.
If there are godd refererences to compatible/notcampatible would be nice to request.

**Comment by paultag** [comment]
I think this is out of scope - this is a hugely complex space, and the possibilities (even for 10 most commonly used licenses) is 100, all of which requires a legal expert to go through the licenses involved, and determine if it's distributable, as well as what the aggregate work is distributed under.

That's not even to mention three licenses (phew!)

It's also confounded complexities in implementation the `GPL-2` *may* be compatable with `-3`, if you can use or later.

@hefee If you want to prototype one, and see how far you can get, I'd love to see mockups and ideas! In the mentime, I'm going to close this, since I'm very unlikely to get to this :)

:+1:
